title: Name  # You can add your name here

logo: logo licorne 2.jpeg # Use a relative path to logo image 

description: Data science and AI in agriculture - where bytes and botany blend for a better world. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: youremail@gmail.com # Allow visitors to contact you
